language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
env:
  - DJANGO=1.4.10
  - DJANGO=1.5.5
  - DJANGO=1.6
  - DJANGO=master
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=1.4.10
install:
  - pip install -q Django==${DJANGO} --use-mirrors
  - pip install -q -r requirements-dev.txt --use-mirrors
  - pip install -q -e . --use-mirrors
before_script:
  - flake8 src/statici18n
  - flake8 tests
script:
  - py.test tests
